# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Dict, List, Mapping, Optional, Tuple, Union
from .. import _utilities, _tables

__all__ = [
    'ServiceQueryKey',
]

@pulumi.output_type
class ServiceQueryKey(dict):
    @property
    @pulumi.getter
    def key(self) -> Optional[str]:
        """
        The value of this Query Key.
        """
        ...

    @property
    @pulumi.getter
    def name(self) -> Optional[str]:
        """
        The Name which should be used for this Search Service. Changing this forces a new Search Service to be created.
        """
        ...

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


