# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Dict, List, Optional, Tuple, Union
from .. import _utilities, _tables

@pulumi.input_type
class ModuleModuleLinkArgs:
    uri: pulumi.Input[str] = pulumi.input_property("uri")
    """
    The uri of the module content (zip or nupkg).
    """
    hash: Optional[pulumi.Input['ModuleModuleLinkHashArgs']] = pulumi.input_property("hash")

    # pylint: disable=no-self-argument
    def __init__(__self__, *, uri: pulumi.Input[str], hash: Optional[pulumi.Input['ModuleModuleLinkHashArgs']] = None) -> None:
        """
        :param pulumi.Input[str] uri: The uri of the module content (zip or nupkg).
        """
        __self__.uri = uri
        __self__.hash = hash

@pulumi.input_type
class ModuleModuleLinkHashArgs:
    algorithm: pulumi.Input[str] = pulumi.input_property("algorithm")
    value: pulumi.Input[str] = pulumi.input_property("value")

    # pylint: disable=no-self-argument
    def __init__(__self__, *, algorithm: pulumi.Input[str], value: pulumi.Input[str]) -> None:
        __self__.algorithm = algorithm
        __self__.value = value

@pulumi.input_type
class RunBookPublishContentLinkArgs:
    uri: pulumi.Input[str] = pulumi.input_property("uri")
    """
    The uri of the runbook content.
    """
    hash: Optional[pulumi.Input['RunBookPublishContentLinkHashArgs']] = pulumi.input_property("hash")
    version: Optional[pulumi.Input[str]] = pulumi.input_property("version")

    # pylint: disable=no-self-argument
    def __init__(__self__, *, uri: pulumi.Input[str], hash: Optional[pulumi.Input['RunBookPublishContentLinkHashArgs']] = None, version: Optional[pulumi.Input[str]] = None) -> None:
        """
        :param pulumi.Input[str] uri: The uri of the runbook content.
        """
        __self__.uri = uri
        __self__.hash = hash
        __self__.version = version

@pulumi.input_type
class RunBookPublishContentLinkHashArgs:
    algorithm: pulumi.Input[str] = pulumi.input_property("algorithm")
    value: pulumi.Input[str] = pulumi.input_property("value")

    # pylint: disable=no-self-argument
    def __init__(__self__, *, algorithm: pulumi.Input[str], value: pulumi.Input[str]) -> None:
        __self__.algorithm = algorithm
        __self__.value = value

@pulumi.input_type
class ScheduleMonthlyOccurrenceArgs:
    day: pulumi.Input[str] = pulumi.input_property("day")
    """
    Day of the occurrence. Must be one of `Monday`, `Tuesday`, `Wednesday`, `Thursday`, `Friday`, `Saturday`, `Sunday`.
    """
    occurrence: pulumi.Input[float] = pulumi.input_property("occurrence")
    """
    Occurrence of the week within the month. Must be between `1` and `5`. `-1` for last week within the month.
    """

    # pylint: disable=no-self-argument
    def __init__(__self__, *, day: pulumi.Input[str], occurrence: pulumi.Input[float]) -> None:
        """
        :param pulumi.Input[str] day: Day of the occurrence. Must be one of `Monday`, `Tuesday`, `Wednesday`, `Thursday`, `Friday`, `Saturday`, `Sunday`.
        :param pulumi.Input[float] occurrence: Occurrence of the week within the month. Must be between `1` and `5`. `-1` for last week within the month.
        """
        __self__.day = day
        __self__.occurrence = occurrence

