// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package core

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to access information about an existing User Assigned Identity.
//
// ## Example Usage
// ### Reference An Existing)
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-azure/sdk/v4/go/azure/authorization"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		example, err := authorization.LookupUserAssignedIdentity(ctx, &authorization.LookupUserAssignedIdentityArgs{
// 			Name:              "name_of_user_assigned_identity",
// 			ResourceGroupName: "name_of_resource_group",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("uaiClientId", example.ClientId)
// 		ctx.Export("uaiPrincipalId", example.PrincipalId)
// 		ctx.Export("uaiTenantId", example.TenantId)
// 		return nil
// 	})
// }
// ```
//
// Deprecated: azure.core.getUserAssignedIdentity has been deprecated in favor of azure.authorization.getUserAssignedIdentity
func GetUserAssignedIdentity(ctx *pulumi.Context, args *GetUserAssignedIdentityArgs, opts ...pulumi.InvokeOption) (*GetUserAssignedIdentityResult, error) {
	var rv GetUserAssignedIdentityResult
	err := ctx.Invoke("azure:core/getUserAssignedIdentity:getUserAssignedIdentity", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUserAssignedIdentity.
type GetUserAssignedIdentityArgs struct {
	// The name of the User Assigned Identity.
	Name string `pulumi:"name"`
	// The name of the Resource Group in which the User Assigned Identity exists.
	ResourceGroupName string `pulumi:"resourceGroupName"`
}

// A collection of values returned by getUserAssignedIdentity.
type GetUserAssignedIdentityResult struct {
	// The Client ID of the User Assigned Identity.
	ClientId string `pulumi:"clientId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The Azure location where the User Assigned Identity exists.
	Location string `pulumi:"location"`
	Name     string `pulumi:"name"`
	// The Service Principal ID of the User Assigned Identity.
	PrincipalId       string `pulumi:"principalId"`
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// A mapping of tags assigned to the User Assigned Identity.
	Tags map[string]string `pulumi:"tags"`
	// The Tenant ID of the User Assigned Identity.
	TenantId string `pulumi:"tenantId"`
}

func GetUserAssignedIdentityApply(ctx *pulumi.Context, args GetUserAssignedIdentityApplyInput, opts ...pulumi.InvokeOption) GetUserAssignedIdentityResultOutput {
	return args.ToGetUserAssignedIdentityApplyOutput().ApplyT(func(v GetUserAssignedIdentityArgs) (GetUserAssignedIdentityResult, error) {
		r, err := GetUserAssignedIdentity(ctx, &v, opts...)
		return *r, err

	}).(GetUserAssignedIdentityResultOutput)
}

// GetUserAssignedIdentityApplyInput is an input type that accepts GetUserAssignedIdentityApplyArgs and GetUserAssignedIdentityApplyOutput values.
// You can construct a concrete instance of `GetUserAssignedIdentityApplyInput` via:
//
//          GetUserAssignedIdentityApplyArgs{...}
type GetUserAssignedIdentityApplyInput interface {
	pulumi.Input

	ToGetUserAssignedIdentityApplyOutput() GetUserAssignedIdentityApplyOutput
	ToGetUserAssignedIdentityApplyOutputWithContext(context.Context) GetUserAssignedIdentityApplyOutput
}

// A collection of arguments for invoking getUserAssignedIdentity.
type GetUserAssignedIdentityApplyArgs struct {
	// The name of the User Assigned Identity.
	Name pulumi.StringInput `pulumi:"name"`
	// The name of the Resource Group in which the User Assigned Identity exists.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
}

func (GetUserAssignedIdentityApplyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUserAssignedIdentityArgs)(nil)).Elem()
}

func (i GetUserAssignedIdentityApplyArgs) ToGetUserAssignedIdentityApplyOutput() GetUserAssignedIdentityApplyOutput {
	return i.ToGetUserAssignedIdentityApplyOutputWithContext(context.Background())
}

func (i GetUserAssignedIdentityApplyArgs) ToGetUserAssignedIdentityApplyOutputWithContext(ctx context.Context) GetUserAssignedIdentityApplyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetUserAssignedIdentityApplyOutput)
}

// A collection of arguments for invoking getUserAssignedIdentity.
type GetUserAssignedIdentityApplyOutput struct{ *pulumi.OutputState }

func (GetUserAssignedIdentityApplyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUserAssignedIdentityArgs)(nil)).Elem()
}

func (o GetUserAssignedIdentityApplyOutput) ToGetUserAssignedIdentityApplyOutput() GetUserAssignedIdentityApplyOutput {
	return o
}

func (o GetUserAssignedIdentityApplyOutput) ToGetUserAssignedIdentityApplyOutputWithContext(ctx context.Context) GetUserAssignedIdentityApplyOutput {
	return o
}

// The name of the User Assigned Identity.
func (o GetUserAssignedIdentityApplyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserAssignedIdentityArgs) string { return v.Name }).(pulumi.StringOutput)
}

// The name of the Resource Group in which the User Assigned Identity exists.
func (o GetUserAssignedIdentityApplyOutput) ResourceGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserAssignedIdentityArgs) string { return v.ResourceGroupName }).(pulumi.StringOutput)
}

// A collection of values returned by getUserAssignedIdentity.
type GetUserAssignedIdentityResultOutput struct{ *pulumi.OutputState }

func (GetUserAssignedIdentityResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUserAssignedIdentityResult)(nil)).Elem()
}

func (o GetUserAssignedIdentityResultOutput) ToGetUserAssignedIdentityResultOutput() GetUserAssignedIdentityResultOutput {
	return o
}

func (o GetUserAssignedIdentityResultOutput) ToGetUserAssignedIdentityResultOutputWithContext(ctx context.Context) GetUserAssignedIdentityResultOutput {
	return o
}

// The Client ID of the User Assigned Identity.
func (o GetUserAssignedIdentityResultOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserAssignedIdentityResult) string { return v.ClientId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetUserAssignedIdentityResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserAssignedIdentityResult) string { return v.Id }).(pulumi.StringOutput)
}

// The Azure location where the User Assigned Identity exists.
func (o GetUserAssignedIdentityResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserAssignedIdentityResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o GetUserAssignedIdentityResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserAssignedIdentityResult) string { return v.Name }).(pulumi.StringOutput)
}

// The Service Principal ID of the User Assigned Identity.
func (o GetUserAssignedIdentityResultOutput) PrincipalId() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserAssignedIdentityResult) string { return v.PrincipalId }).(pulumi.StringOutput)
}

func (o GetUserAssignedIdentityResultOutput) ResourceGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserAssignedIdentityResult) string { return v.ResourceGroupName }).(pulumi.StringOutput)
}

// A mapping of tags assigned to the User Assigned Identity.
func (o GetUserAssignedIdentityResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetUserAssignedIdentityResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

// The Tenant ID of the User Assigned Identity.
func (o GetUserAssignedIdentityResultOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserAssignedIdentityResult) string { return v.TenantId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetUserAssignedIdentityApplyOutput{})
	pulumi.RegisterOutputType(GetUserAssignedIdentityResultOutput{})
}
