// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package privatelink

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to access endpoint connection information about an existing Private Link Service.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-azure/sdk/v4/go/azure/privatelink"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		example, err := privatelink.GetServiceEndpointConnections(ctx, &privatelink.GetServiceEndpointConnectionsArgs{
// 			ServiceId:         azurerm_private_link_service.Example.Id,
// 			ResourceGroupName: azurerm_resource_group.Example.Name,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("privateEndpointStatus", example.PrivateEndpointConnections[0].Status)
// 		return nil
// 	})
// }
// ```
func GetServiceEndpointConnections(ctx *pulumi.Context, args *GetServiceEndpointConnectionsArgs, opts ...pulumi.InvokeOption) (*GetServiceEndpointConnectionsResult, error) {
	var rv GetServiceEndpointConnectionsResult
	err := ctx.Invoke("azure:privatelink/getServiceEndpointConnections:getServiceEndpointConnections", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServiceEndpointConnections.
type GetServiceEndpointConnectionsArgs struct {
	// The name of the resource group in which the private link service resides.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// The resource ID of the private link service.
	ServiceId string `pulumi:"serviceId"`
}

// A collection of values returned by getServiceEndpointConnections.
type GetServiceEndpointConnectionsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id                         string                                                   `pulumi:"id"`
	Location                   string                                                   `pulumi:"location"`
	PrivateEndpointConnections []GetServiceEndpointConnectionsPrivateEndpointConnection `pulumi:"privateEndpointConnections"`
	ResourceGroupName          string                                                   `pulumi:"resourceGroupName"`
	ServiceId                  string                                                   `pulumi:"serviceId"`
	// The name of the private link service.
	ServiceName string `pulumi:"serviceName"`
}

func GetServiceEndpointConnectionsApply(ctx *pulumi.Context, args GetServiceEndpointConnectionsApplyInput, opts ...pulumi.InvokeOption) GetServiceEndpointConnectionsResultOutput {
	return args.ToGetServiceEndpointConnectionsApplyOutput().ApplyT(func(v GetServiceEndpointConnectionsArgs) (GetServiceEndpointConnectionsResult, error) {
		r, err := GetServiceEndpointConnections(ctx, &v, opts...)
		return *r, err

	}).(GetServiceEndpointConnectionsResultOutput)
}

// GetServiceEndpointConnectionsApplyInput is an input type that accepts GetServiceEndpointConnectionsApplyArgs and GetServiceEndpointConnectionsApplyOutput values.
// You can construct a concrete instance of `GetServiceEndpointConnectionsApplyInput` via:
//
//          GetServiceEndpointConnectionsApplyArgs{...}
type GetServiceEndpointConnectionsApplyInput interface {
	pulumi.Input

	ToGetServiceEndpointConnectionsApplyOutput() GetServiceEndpointConnectionsApplyOutput
	ToGetServiceEndpointConnectionsApplyOutputWithContext(context.Context) GetServiceEndpointConnectionsApplyOutput
}

// A collection of arguments for invoking getServiceEndpointConnections.
type GetServiceEndpointConnectionsApplyArgs struct {
	// The name of the resource group in which the private link service resides.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
	// The resource ID of the private link service.
	ServiceId pulumi.StringInput `pulumi:"serviceId"`
}

func (GetServiceEndpointConnectionsApplyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServiceEndpointConnectionsArgs)(nil)).Elem()
}

func (i GetServiceEndpointConnectionsApplyArgs) ToGetServiceEndpointConnectionsApplyOutput() GetServiceEndpointConnectionsApplyOutput {
	return i.ToGetServiceEndpointConnectionsApplyOutputWithContext(context.Background())
}

func (i GetServiceEndpointConnectionsApplyArgs) ToGetServiceEndpointConnectionsApplyOutputWithContext(ctx context.Context) GetServiceEndpointConnectionsApplyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetServiceEndpointConnectionsApplyOutput)
}

// A collection of arguments for invoking getServiceEndpointConnections.
type GetServiceEndpointConnectionsApplyOutput struct{ *pulumi.OutputState }

func (GetServiceEndpointConnectionsApplyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServiceEndpointConnectionsArgs)(nil)).Elem()
}

func (o GetServiceEndpointConnectionsApplyOutput) ToGetServiceEndpointConnectionsApplyOutput() GetServiceEndpointConnectionsApplyOutput {
	return o
}

func (o GetServiceEndpointConnectionsApplyOutput) ToGetServiceEndpointConnectionsApplyOutputWithContext(ctx context.Context) GetServiceEndpointConnectionsApplyOutput {
	return o
}

// The name of the resource group in which the private link service resides.
func (o GetServiceEndpointConnectionsApplyOutput) ResourceGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceEndpointConnectionsArgs) string { return v.ResourceGroupName }).(pulumi.StringOutput)
}

// The resource ID of the private link service.
func (o GetServiceEndpointConnectionsApplyOutput) ServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceEndpointConnectionsArgs) string { return v.ServiceId }).(pulumi.StringOutput)
}

// A collection of values returned by getServiceEndpointConnections.
type GetServiceEndpointConnectionsResultOutput struct{ *pulumi.OutputState }

func (GetServiceEndpointConnectionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServiceEndpointConnectionsResult)(nil)).Elem()
}

func (o GetServiceEndpointConnectionsResultOutput) ToGetServiceEndpointConnectionsResultOutput() GetServiceEndpointConnectionsResultOutput {
	return o
}

func (o GetServiceEndpointConnectionsResultOutput) ToGetServiceEndpointConnectionsResultOutputWithContext(ctx context.Context) GetServiceEndpointConnectionsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetServiceEndpointConnectionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceEndpointConnectionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetServiceEndpointConnectionsResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceEndpointConnectionsResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o GetServiceEndpointConnectionsResultOutput) PrivateEndpointConnections() GetServiceEndpointConnectionsPrivateEndpointConnectionArrayOutput {
	return o.ApplyT(func(v GetServiceEndpointConnectionsResult) []GetServiceEndpointConnectionsPrivateEndpointConnection {
		return v.PrivateEndpointConnections
	}).(GetServiceEndpointConnectionsPrivateEndpointConnectionArrayOutput)
}

func (o GetServiceEndpointConnectionsResultOutput) ResourceGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceEndpointConnectionsResult) string { return v.ResourceGroupName }).(pulumi.StringOutput)
}

func (o GetServiceEndpointConnectionsResultOutput) ServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceEndpointConnectionsResult) string { return v.ServiceId }).(pulumi.StringOutput)
}

// The name of the private link service.
func (o GetServiceEndpointConnectionsResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceEndpointConnectionsResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServiceEndpointConnectionsApplyOutput{})
	pulumi.RegisterOutputType(GetServiceEndpointConnectionsResultOutput{})
}
