# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Dict, List, Optional, Tuple, Union
from .. import _utilities, _tables

@pulumi.input_type
class ServerIpv4FirewallRuleArgs:
    name: pulumi.Input[str] = pulumi.input_property("name")
    """
    Specifies the name of the firewall rule.
    """
    range_end: pulumi.Input[str] = pulumi.input_property("rangeEnd")
    """
    End of the firewall rule range as IPv4 address.
    """
    range_start: pulumi.Input[str] = pulumi.input_property("rangeStart")
    """
    Start of the firewall rule range as IPv4 address.
    """

    # pylint: disable=no-self-argument
    def __init__(__self__, *, name: pulumi.Input[str], range_end: pulumi.Input[str], range_start: pulumi.Input[str]) -> None:
        """
        :param pulumi.Input[str] name: Specifies the name of the firewall rule.
        :param pulumi.Input[str] range_end: End of the firewall rule range as IPv4 address.
        :param pulumi.Input[str] range_start: Start of the firewall rule range as IPv4 address.
        """
        __self__.name = name
        __self__.range_end = range_end
        __self__.range_start = range_start

