# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Dict, List, Optional, Tuple, Union
from .. import _utilities, _tables

__all__ = [
    'ServerIpv4FirewallRule',
]

@pulumi.output_type
class ServerIpv4FirewallRule(dict):
    name: str = pulumi.output_property("name")
    """
    Specifies the name of the firewall rule.
    """
    range_end: str = pulumi.output_property("rangeEnd")
    """
    End of the firewall rule range as IPv4 address.
    """
    range_start: str = pulumi.output_property("rangeStart")
    """
    Start of the firewall rule range as IPv4 address.
    """

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


