# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Dict, List, Optional, Tuple, Union
from .. import _utilities, _tables

__all__ = [
    'AccountActiveDirectory',
    'VolumeExportPolicyRule',
]

@pulumi.output_type
class AccountActiveDirectory(dict):
    dns_servers: List[str] = pulumi.output_property("dnsServers")
    """
    A list of DNS server IP addresses for the Active Directory domain. Only allows `IPv4` address.
    """
    domain: str = pulumi.output_property("domain")
    """
    The name of the Active Directory domain.
    """
    organizational_unit: Optional[str] = pulumi.output_property("organizationalUnit")
    """
    The Organizational Unit (OU) within the Active Directory Domain.
    """
    password: str = pulumi.output_property("password")
    """
    The password associated with the `username`.
    """
    smb_server_name: str = pulumi.output_property("smbServerName")
    """
    The NetBIOS name which should be used for the NetApp SMB Server, which will be registered as a computer account in the AD and used to mount volumes.
    """
    username: str = pulumi.output_property("username")
    """
    The Username of Active Directory Domain Administrator.
    """

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class VolumeExportPolicyRule(dict):
    allowed_clients: List[str] = pulumi.output_property("allowedClients")
    """
    A list of allowed clients IPv4 addresses.
    """
    cifs_enabled: Optional[bool] = pulumi.output_property("cifsEnabled")
    """
    Is the CIFS protocol allowed?
    """
    nfsv3_enabled: Optional[bool] = pulumi.output_property("nfsv3Enabled")
    """
    Is the NFSv3 protocol allowed?
    """
    nfsv4_enabled: Optional[bool] = pulumi.output_property("nfsv4Enabled")
    """
    Is the NFSv4 protocol allowed?
    """
    protocols_enabled: Optional[str] = pulumi.output_property("protocolsEnabled")
    """
    A list of allowed protocols. Valid values include `CIFS`, `NFSv3`, or `NFSv4.1`. Only one value is supported at this time. This replaces the previous arguments: `cifs_enabled`, `nfsv3_enabled` and `nfsv4_enabled`.
    """
    rule_index: float = pulumi.output_property("ruleIndex")
    """
    The index number of the rule.
    """
    unix_read_only: Optional[bool] = pulumi.output_property("unixReadOnly")
    """
    Is the file system on unix read only?
    """
    unix_read_write: Optional[bool] = pulumi.output_property("unixReadWrite")
    """
    Is the file system on unix read and write?
    """

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


