# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

# Export this package's modules as members:
from .alert_rule_ms_security_incident import *
from .alert_rule_scheduled import *
from .get_alert_rule import *

import pulumi

class Module(pulumi.runtime.ResourceModule):
    def version(self):
        return None

    def construct(self, name: str, typ: str, urn: str) -> pulumi.Resource:
        if typ == "azure:sentinel/alertRuleMsSecurityIncident:AlertRuleMsSecurityIncident":
            return AlertRuleMsSecurityIncident(name, pulumi.ResourceOptions(urn=urn))
        elif typ == "azure:sentinel/alertRuleScheduled:AlertRuleScheduled":
            return AlertRuleScheduled(name, pulumi.ResourceOptions(urn=urn))
        else:
            raise Exception(f"unknown resource type {typ}")


_module_instance = Module()
pulumi.runtime.register_resource_module("azure", "sentinel/alertRuleMsSecurityIncident", _module_instance)
pulumi.runtime.register_resource_module("azure", "sentinel/alertRuleScheduled", _module_instance)
