// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package automation

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to access information about an existing Automation Int Variable.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-azure/sdk/v4/go/azure/automation"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		example, err := automation.LookupIntVariable(ctx, &automation.LookupIntVariableArgs{
// 			Name:                  "tfex-example-var",
// 			ResourceGroupName:     "tfex-example-rg",
// 			AutomationAccountName: "tfex-example-account",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("variableId", example.Id)
// 		return nil
// 	})
// }
// ```
func LookupIntVariable(ctx *pulumi.Context, args *LookupIntVariableArgs, opts ...pulumi.InvokeOption) (*LookupIntVariableResult, error) {
	var rv LookupIntVariableResult
	err := ctx.Invoke("azure:automation/getIntVariable:getIntVariable", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIntVariable.
type LookupIntVariableArgs struct {
	// The name of the automation account in which the Automation Variable exists.
	AutomationAccountName string `pulumi:"automationAccountName"`
	// The name of the Automation Variable.
	Name string `pulumi:"name"`
	// The Name of the Resource Group where the automation account exists.
	ResourceGroupName string `pulumi:"resourceGroupName"`
}

// A collection of values returned by getIntVariable.
type LookupIntVariableResult struct {
	AutomationAccountName string `pulumi:"automationAccountName"`
	// The description of the Automation Variable.
	Description string `pulumi:"description"`
	// Specifies if the Automation Variable is encrypted. Defaults to `false`.
	Encrypted bool `pulumi:"encrypted"`
	// The provider-assigned unique ID for this managed resource.
	Id                string `pulumi:"id"`
	Name              string `pulumi:"name"`
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// The value of the Automation Variable as a `integer`.
	Value int `pulumi:"value"`
}

func LookupIntVariableApply(ctx *pulumi.Context, args LookupIntVariableApplyInput, opts ...pulumi.InvokeOption) LookupIntVariableResultOutput {
	return args.ToLookupIntVariableApplyOutput().ApplyT(func(v LookupIntVariableArgs) (LookupIntVariableResult, error) {
		r, err := LookupIntVariable(ctx, &v, opts...)
		return *r, err

	}).(LookupIntVariableResultOutput)
}

// LookupIntVariableApplyInput is an input type that accepts LookupIntVariableApplyArgs and LookupIntVariableApplyOutput values.
// You can construct a concrete instance of `LookupIntVariableApplyInput` via:
//
//          LookupIntVariableApplyArgs{...}
type LookupIntVariableApplyInput interface {
	pulumi.Input

	ToLookupIntVariableApplyOutput() LookupIntVariableApplyOutput
	ToLookupIntVariableApplyOutputWithContext(context.Context) LookupIntVariableApplyOutput
}

// A collection of arguments for invoking getIntVariable.
type LookupIntVariableApplyArgs struct {
	// The name of the automation account in which the Automation Variable exists.
	AutomationAccountName pulumi.StringInput `pulumi:"automationAccountName"`
	// The name of the Automation Variable.
	Name pulumi.StringInput `pulumi:"name"`
	// The Name of the Resource Group where the automation account exists.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
}

func (LookupIntVariableApplyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIntVariableArgs)(nil)).Elem()
}

func (i LookupIntVariableApplyArgs) ToLookupIntVariableApplyOutput() LookupIntVariableApplyOutput {
	return i.ToLookupIntVariableApplyOutputWithContext(context.Background())
}

func (i LookupIntVariableApplyArgs) ToLookupIntVariableApplyOutputWithContext(ctx context.Context) LookupIntVariableApplyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LookupIntVariableApplyOutput)
}

// A collection of arguments for invoking getIntVariable.
type LookupIntVariableApplyOutput struct{ *pulumi.OutputState }

func (LookupIntVariableApplyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIntVariableArgs)(nil)).Elem()
}

func (o LookupIntVariableApplyOutput) ToLookupIntVariableApplyOutput() LookupIntVariableApplyOutput {
	return o
}

func (o LookupIntVariableApplyOutput) ToLookupIntVariableApplyOutputWithContext(ctx context.Context) LookupIntVariableApplyOutput {
	return o
}

// The name of the automation account in which the Automation Variable exists.
func (o LookupIntVariableApplyOutput) AutomationAccountName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIntVariableArgs) string { return v.AutomationAccountName }).(pulumi.StringOutput)
}

// The name of the Automation Variable.
func (o LookupIntVariableApplyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIntVariableArgs) string { return v.Name }).(pulumi.StringOutput)
}

// The Name of the Resource Group where the automation account exists.
func (o LookupIntVariableApplyOutput) ResourceGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIntVariableArgs) string { return v.ResourceGroupName }).(pulumi.StringOutput)
}

// A collection of values returned by getIntVariable.
type LookupIntVariableResultOutput struct{ *pulumi.OutputState }

func (LookupIntVariableResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIntVariableResult)(nil)).Elem()
}

func (o LookupIntVariableResultOutput) ToLookupIntVariableResultOutput() LookupIntVariableResultOutput {
	return o
}

func (o LookupIntVariableResultOutput) ToLookupIntVariableResultOutputWithContext(ctx context.Context) LookupIntVariableResultOutput {
	return o
}

func (o LookupIntVariableResultOutput) AutomationAccountName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIntVariableResult) string { return v.AutomationAccountName }).(pulumi.StringOutput)
}

// The description of the Automation Variable.
func (o LookupIntVariableResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIntVariableResult) string { return v.Description }).(pulumi.StringOutput)
}

// Specifies if the Automation Variable is encrypted. Defaults to `false`.
func (o LookupIntVariableResultOutput) Encrypted() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIntVariableResult) bool { return v.Encrypted }).(pulumi.BoolOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupIntVariableResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIntVariableResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupIntVariableResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIntVariableResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupIntVariableResultOutput) ResourceGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIntVariableResult) string { return v.ResourceGroupName }).(pulumi.StringOutput)
}

// The value of the Automation Variable as a `integer`.
func (o LookupIntVariableResultOutput) Value() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIntVariableResult) int { return v.Value }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIntVariableApplyOutput{})
	pulumi.RegisterOutputType(LookupIntVariableResultOutput{})
}
